backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "src/index.njk"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Text", name: "hero_text", widget: "string" }
          - { label: "Services", name: "services", widget: "list" }